name: Publish

on: 
  push:
    tags:
    - 'v*'
env:
  PROJECT_NAME: 'tone'
  PROJECT_PATH: 'tone/tone.csproj'
  PROJECT_OUTPUT_PATH: ${{ github.workspace }}/output/
  DOTNET_VERSION: '6.0.300'
  DOTNET_FRAMEWORK: 'net6.0'
jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: [
          'linux', 
          'linux-arm',
          'linux-arm64',
          'windows', 
          'macOS',
          'macOS-arm'
        ]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: linux-arm
            os: ubuntu-latest
            target: linux-arm    
          - kind: linux-arm64
            os: ubuntu-latest
            target: linux-arm64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
          - kind: macOS-arm
            os: macos-latest
            target: osx-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: "https://nuget.pkg.github.com/sandreas/index.json"
        env:
            NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Get version
        id: version
        uses: battila7/get-version-action@v2

      - name: Build
        shell: bash
        run: |
          release_name="${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version-without-v }}-${{ matrix.target }}"
          dotnet publish ${{ env.PROJECT_PATH }} --framework ${{ env.DOTNET_FRAMEWORK }} --runtime "${{ matrix.target }}" -c Release -p:PublishSingleFile=true --self-contained true -p:PublishReadyToRun=true -p:PublishTrimmed=true -o "$release_name"
          
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./${release_name}/tone.exe"
          else
            tar czvf "${release_name}.tar.gz" "$release_name/tone"
          fi
          rm -r "$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version-without-v }}-${{ matrix.target }}*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
