name: release

on: 
  push:
    tags:
    - 'v*'
env:
  PROJECT_NAME: 'tone'
  PROJECT_PATH: 'tone/tone.csproj'
  PROJECT_OUTPUT_PATH: ${{ github.workspace }}/output/
  DOTNET_VERSION: '6.0.300'
  DOTNET_FRAMEWORK: 'net6.0'
jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: [
          'linux', 
          'linux-arm',
          'linux-arm64',
          'windows', 
          'macOS',
          'macOS-arm'
        ]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: linux-arm
            os: ubuntu-latest
            target: linux-arm    
          - kind: linux-arm64
            os: ubuntu-latest
            target: linux-arm64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
          - kind: macOS-arm
            os: macos-latest
            target: osx-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: "https://nuget.pkg.github.com/sandreas/index.json"
        env:
            NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Get version
        id: version
        uses: battila7/get-version-action@v2

      - name: Build
        id: build
        shell: bash
        run: |
          release_name="${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version-without-v }}-${{ matrix.target }}"
          release_notes="$(sed 's/%/%25/g;s/\r/%0D/g;' ${{ env.PROJECT_NAME }}/doc/release/release-notes-${{ steps.version.outputs.version }}.md | sed ':a;N;$!ba;s/\n/%0A/g')"
          echo "::set-output name=release_notes::$release_notes"
          
          dotnet publish ${{ env.PROJECT_PATH }} --framework ${{ env.DOTNET_FRAMEWORK }} --runtime "${{ matrix.target }}" -c Release -p:PublishSingleFile=true --self-contained true -p:PublishReadyToRun=true -p:PublishTrimmed=true -o "$release_name"
          
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./${release_name}/tone.exe"
          else
            tar czvf "${release_name}.tar.gz" "$release_name/tone"
          fi
          rm -r "$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version-without-v }}-${{ matrix.target }}*"
          body: "${{ steps.build.outputs.release_notes }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    needs: release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Prepare docker args
        id: prepare_docker_args
        shell: bash        
        run: |
          echo "targetplatform: $TARGETPLATFORM"
          
          case "$TARGETPLATFORM" in
            linux/arm/v6) 
              FFMPEG_IMAGE=collelog/ffmpeg:4.4-alpine-arm32v6
              FFMPEG_PATH="/usr/local/bin/ffmpeg"
              SUFFIX="arm.tar.gz"
              ;;
            linux/arm/v7) 
              FFMPEG_IMAGE=collelog/ffmpeg:4.4-alpine-arm32v7
              FFMPEG_PATH="/usr/local/bin/ffmpeg"
              SUFFIX="arm.tar.gz"
              ;;
            linux/arm64) 
              FFMPEG_IMAGE=mwader/static-ffmpeg:5.0.1-3
              FFMPEG_PATH="/ffmpeg"
              SUFFIX="arm64.tar.gz"
              ;;
            linux/amd64) 
              FFMPEG_IMAGE=mwader/static-ffmpeg:5.0.1-3
              FFMPEG_PATH="/ffmpeg"
              SUFFIX="x64.tar.gz"
              ;;
          esac
          
          TONE_VERSION=$(sed 's/^v//g' <<< "${{ github.ref_name }}")
          TONE_DOWNLOAD_URL="https://github.com/sandreas/tone/releases/download/v$TONE_VERSION/tone-$TONE_VERSION-linux-$SUFFIX"
          
          # echo "TONE_DOWNLOAD_URL=$TONE_DOWNLOAD_URL" >> $GITHUB_ENV
          # echo "FFMPEG_IMAGE=$FFMPEG_IMAGE" >> $GITHUB_ENV
          # echo "FFMPEG_PATH=$FFMPEG_PATH" >> $GITHUB_ENV      
          
          echo "::set-output name=TONE_DOWNLOAD_URL::$TONE_DOWNLOAD_URL"
          echo "::set-output name=FFMPEG_IMAGE::$FFMPEG_IMAGE"
          echo "::set-output name=FFMPEG_PATH::$FFMPEG_PATH"

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: tone/
          file: tone/Dockerfile.release
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: sandreas/tone:${{ github.ref_name }}
          build-args: |
            TONE_DOWNLOAD_URL=${{ steps.prepare_docker_args.outputs.TONE_DOWNLOAD_URL }}
            FFMPEG_IMAGE=${{ steps.prepare_docker_args.outputs.FFMPEG_IMAGE }}
            FFMPEG_PATH=${{ steps.prepare_docker_args.outputs.FFMPEG_PATH }}
            